### PR TITLE
enable admin interface, add TodoItem string representation

### PR DESCRIPTION
**Pull request by Nighoo**
* admin ui rules
* model needs string representation

### CODE REVIEW

**Comment by notandy** [comment]
:-1:

**Comment by Nighoo** [comment]
:+1: #yolo

**Comment by notandy** [comment]
#yoloyolo

**Comment by MetalMatze** [comment]
:hushed:

**Comment by Nighoo** [comment]
Oh, please be more verbose. I do not understand your comments!

**Comment by Gjum** [comment]
To separate the discussions about the two changes you want to have merged, please open a pull requests for each proposed change.

**Comment by Nighoo** [comment]
Oargh... both are related. The string representation is only used by the admin interface.

**Pull request closed without merging**
